### ISSUE TITLE
Default variable, mixin, and function patterns should not error on `_` prefix used for private sass contructs

### ISSUE THREAD

**Issue by mirisuzanne** [stylelint-scss/stylelint-config-standard-scss#12]
Sass requires the _ prefix as a consistent pattern to make variables, mixins, or function "private" to a particular module. That should be allowed even when the naming pattern does not otherwise allow underscores.

**Comment by kristerkari** [comment]
@mirisuzanne There was a somewhat recent fix to allow private variables/functions/mixins using `-` instead of `_` (kebab case):
https://github.com/stylelint-scss/stylelint-config-standard-scss/pull/8

From what I understood, it works the same way. Is there something that would not work using `-`?

**Comment by mirisuzanne** [comment]
Yeah - I suppose that works fine from a Sass perspective, I just don't _think_ of it. 

Ok, I can work with that. Thanks.

**Comment by nachtfunke** [comment]
I'm running into this exact issue but I am not really ready yet to switch to a different _flavour_ of making private members. Is there maybe a way to configure what syntax should be used to make something private? As it is, all private members defined with `_` are marked and I don't really want to switch to `-` because of this. I wondered, if there is a way around it?
